receivers:
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:    
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
    
exporters:
  datadog/api: 
    hostname: telemetrylabs
    env: development
    service: webapi.opentelemetry.datadog
    version: 3
    tags:
      - service:webapi.opentelemetry.datadog
      - env:development
    api:
      key: 2f79ac1503bf67bb403fb09639d4677a

#exporters:
#  datadog:
#    api:
#      key: 2f79ac1503bf67bb403fb09639d4677a

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [datadog/api]
#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [datadog/api]